language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: dIEQJWLy7YAC+ZrgpZYQAKWjWtFHYtfyINmwVkPrtK53fskCxS7mbgJY/Jjkh07nLO0WdMVzrLnYsXG6v1uDm6rG/i2JbZIHDZJLlXdUFcSZINg7lKemsr6futBUqYapSv7SWxAmcpk247znbHIHEJCvGoWchBfG29422YcJlePtaKCP+q46c/cE409iykieG2qxTRX6mD+oPfCJLWGDjhIO3B/zUcxklaO52EaTC3YfacRKgLWP1RXcAGxq5oiqWcsA91ywMIba97SLpdDvhvci7Zsg1LDVuELoLNkr4TN5tfnY9uRcSAaSpYfNaC9AkE7YvRNMDaJKiflvb9TLWK6SeE+zitH4QDbOv6/fT7JOSu+eFNgETxb+xGVtXn2ttGo7OQVfUEv6eRq8sdkdR3h39E3gSS/a2A5o7im3hXiPp7Xr9gXLsvmmltaaj37ovyANaVKC7M4bRIHXrkh+cVcEpOsQFyF4j+9K3cP2Sue9pihPpm3pYCmcnYBzRBA0YYZ5aS7TLw8rYR+i+gc9CQR2DJ5mrUbg10Xf9u72cpdTPfMvgntjkC3iMNyuOyx/cVbhEKbt/SZOsAfNedW0CrR0++5mX8ni3d6qWuXvuFXp9G89JvTpmsAkTLogO4OvLI5LgcXRbTD8GbB8GTMLIq3Ah7HfgKwHiwHX5pEFf5E=
  - secure: y+GgR3c0109QdN0LK6ac6NZVI7loxzgqtPYOIEJVajTNI0S0RCSNv3Kh+GS3F3/fZ4mNcYY5UKEkiEPN5JYhXjk1ZDKPTWzbmoOLylBmIGfPoFmQIvK6oeD41q0cP5WRbIr8dyKEiXr6EtXKwQ50sHxocGT3CTt8nyNUqA6UCkjgjJNa9Utvh+SeuULR9zO6PaqEM3LScRTNHbgqS6t1Ir/a162YFAEAdvlNxGr2q/7Mtwi07dr/TIF2N7K/1yc7e7ZaN70io+CWTKQbViLX/NPacjw27uUOLytJCXPjdMCnZoEVgLIXXD5yJWpls54YJid9V92oep8UIJGgESju2EviOSgRPegZQXGLpMhzmG3Dpq4fd51CEUP4sNQGxOZeMos/6cTouB4rHGbMfDtnj61QjVqZha3Tr8hl18Q17YG9fbl5YiC2oPvTBzrrGClvoEYam0lOchP7b4GSNfVCxTRCVHt6hogfP850A+k/MvOcz1i1M/+dYKh+60nR6cpaaZ7t6BVpoXEMh9gaIZCoItasxOMneVurPiGKm8UoYj2Mv69DSFDH82GYhR59z3kBUYobyjLV51VLhepiEihYgNS3uvIbp84Pxp6lJEhoW4qMJjHjoZMxbwc2nfC7ZbRSIobInjydxncigGqpcyZvisJ2FlCmikTcfa8x6guOQac=
